if(NOT DEFINED PROJECT_ROOT)
    set(PROJECT_ROOT "${CMAKE_SOURCE_DIR}")
endif()

message(STATUS "Cleaning generated build directories under ${PROJECT_ROOT}")

file(GLOB build_dirs LIST_DIRECTORIES true "${PROJECT_ROOT}/build*")
foreach(build_dir IN LISTS build_dirs)
    if(IS_DIRECTORY "${build_dir}")
        if("${build_dir}" STREQUAL "${CMAKE_BINARY_DIR}")
            continue()
        endif()
        file(REMOVE_RECURSE "${build_dir}")
    endif()
endforeach()

set(installed_root "${PROJECT_ROOT}/third_party/installed")
if(EXISTS "${installed_root}")
    file(GLOB installed_items RELATIVE "${installed_root}" "${installed_root}/*")
    foreach(item IN LISTS installed_items)
        set(item_path "${installed_root}/${item}")
        if(EXISTS "${item_path}" AND NOT "${item}" STREQUAL ".gitkeep")
            file(REMOVE_RECURSE "${item_path}")
        endif()
    endforeach()
endif()

set(src_root "${PROJECT_ROOT}/third_party/src")
if(EXISTS "${src_root}")
    file(GLOB src_items RELATIVE "${src_root}" "${src_root}/*")
    foreach(item IN LISTS src_items)
        set(item_path "${src_root}/${item}")
        if(EXISTS "${item_path}" AND NOT "${item}" STREQUAL ".gitkeep")
            file(REMOVE_RECURSE "${item_path}")
        endif()
    endforeach()
endif()

message(STATUS "Clean complete.")
