#pragma once

#include "bgi_types.h"

BGI_API void BGI_CALL arc(int x, int y, int stangle, int endangle, int radius);
BGI_API void BGI_CALL bar(int left, int top, int right, int bottom);
BGI_API void BGI_CALL bar3d(int left, int top, int right, int bottom, int depth, int topflag);
BGI_API void BGI_CALL circle(int x, int y, int radius);
BGI_API void BGI_CALL cleardevice(void);
BGI_API void BGI_CALL clearviewport(void);
BGI_API void BGI_CALL closegraph(void);
BGI_API void BGI_CALL delay(int millisec);
BGI_API void BGI_CALL detectgraph(int *graphdriver, int *graphmode);
BGI_API void BGI_CALL drawpoly(int numpoints, const int *polypoints);
BGI_API void BGI_CALL ellipse(int x, int y, int stangle, int endangle, int xradius, int yradius);
BGI_API void BGI_CALL fillellipse(int x, int y, int xradius, int yradius);
BGI_API void BGI_CALL fillpoly(int numpoints, const int *polypoints);
BGI_API void BGI_CALL floodfill(int x, int y, int border);
BGI_API int BGI_CALL getactivepage(void);
BGI_API void BGI_CALL getarccoords(bgi::arccoordstype *arccoords);
BGI_API void BGI_CALL getaspectratio(int *xasp, int *yasp);
BGI_API int BGI_CALL getbkcolor(void);
BGI_API int BGI_CALL getcolor(void);
BGI_API bgi::palettetype *BGI_CALL getdefaultpalette(void);
BGI_API char *BGI_CALL getdrivername(void);
BGI_API void BGI_CALL getfillpattern(char *pattern);
BGI_API void BGI_CALL getfillsettings(bgi::fillsettingstype *fillinfo);
BGI_API int BGI_CALL getgraphmode(void);
BGI_API void BGI_CALL getimage(int left, int top, int right, int bottom, void *bitmap);
BGI_API void BGI_CALL getlinesettings(bgi::linesettingstype *lineinfo);
BGI_API int BGI_CALL getmaxcolor(void);
BGI_API int BGI_CALL getmaxheight(void);
BGI_API int BGI_CALL getmaxmode(void);
BGI_API int BGI_CALL getmaxwidth(void);
BGI_API int BGI_CALL getmaxx(void);
BGI_API int BGI_CALL getmaxy(void);
BGI_API char *BGI_CALL getmodename(int mode_number);
BGI_API void BGI_CALL getmoderange(int graphdriver, int *lomode, int *himode);
BGI_API void BGI_CALL getpalette(bgi::palettetype *palette);
BGI_API int BGI_CALL getpalettesize(void);
BGI_API int BGI_CALL getpixel(int x, int y);
BGI_API void BGI_CALL gettextsettings(bgi::textsettingstype *texttypeinfo);
BGI_API void BGI_CALL getviewsettings(bgi::viewporttype *viewport);
BGI_API int BGI_CALL getvisualpage(void);
BGI_API int BGI_CALL getwindowheight(void);
BGI_API int BGI_CALL getwindowwidth(void);
BGI_API int BGI_CALL getx(void);
BGI_API int BGI_CALL gety(void);
BGI_API void BGI_CALL graphdefaults(void);
BGI_API char *BGI_CALL grapherrormsg(int errorcode);
BGI_API int BGI_CALL graphresult(void);
BGI_API unsigned BGI_CALL imagesize(int left, int top, int right, int bottom);
BGI_API void BGI_CALL initgraph(int *graphdriver, int *graphmode, char *pathtodriver);
BGI_API int BGI_CALL initwindow(int width, int height, const char *title, int left, int top, int dbflag, int closeflag);
BGI_API int BGI_CALL installuserdriver(char *name, void *detect);
BGI_API int BGI_CALL installuserfont(char *name);
BGI_API void BGI_CALL line(int x1, int y1, int x2, int y2);
BGI_API void BGI_CALL linerel(int dx, int dy);
BGI_API void BGI_CALL lineto(int x, int y);
BGI_API void BGI_CALL moverel(int dx, int dy);
BGI_API void BGI_CALL moveto(int x, int y);
BGI_API void BGI_CALL outtext(char *textstring);
BGI_API void BGI_CALL outtextxy(int x, int y, char *textstring);
BGI_API void BGI_CALL pieslice(int x, int y, int stangle, int endangle, int radius);
BGI_API void BGI_CALL putimage(int left, int top, void *bitmap, int op);
BGI_API void BGI_CALL putpixel(int x, int y, int color);
BGI_API void BGI_CALL rectangle(int left, int top, int right, int bottom);
BGI_API int BGI_CALL registerbgidriver(void (*driver)(void));
BGI_API int BGI_CALL registerbgifont(void (*font)(void));
BGI_API void BGI_CALL restorecrtmode(void);
BGI_API void BGI_CALL sector(int x, int y, int stangle, int endangle, int xradius, int yradius);
BGI_API void BGI_CALL setactivepage(int page);
BGI_API void BGI_CALL setallpalette(const bgi::palettetype *palette);
BGI_API void BGI_CALL setaspectratio(int xasp, int yasp);
BGI_API void BGI_CALL setbkcolor(int color);
BGI_API void BGI_CALL setcolor(int color);
BGI_API void BGI_CALL setfillpattern(char *upattern, int color);
BGI_API void BGI_CALL setfillstyle(int pattern, int color);
BGI_API unsigned BGI_CALL setgraphbufsize(unsigned bufsize);
BGI_API void BGI_CALL setgraphmode(int mode);
BGI_API void BGI_CALL setlinestyle(int linestyle, unsigned upattern, int thickness);
BGI_API void BGI_CALL setpalette(int colornum, int color);
BGI_API void BGI_CALL setrgbpalette(int colornum, int red, int green, int blue);
BGI_API void BGI_CALL settextjustify(int horiz, int vert);
BGI_API void BGI_CALL settextstyle(int font, int direction, int charsize);
BGI_API void BGI_CALL setusercharsize(int multx, int divx, int multy, int divy);
BGI_API void BGI_CALL setviewport(int left, int top, int right, int bottom, int clip);
BGI_API void BGI_CALL setvisualpage(int page);
BGI_API void BGI_CALL setwritemode(int mode);
BGI_API int BGI_CALL swapbuffers(void);
BGI_API int BGI_CALL textheight(char *textstring);
BGI_API int BGI_CALL textwidth(char *textstring);